"""Add user_answers table

Revision ID: 7978ca2f9987
Revises: 
Create Date: 2024-12-23 18:36:10.614799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7978ca2f9987'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_answers',
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=120), nullable=False),
    sa.Column('q_id', sa.Integer(), nullable=False),
    sa.Column('chosen_option', sa.String(length=2), nullable=False),
    sa.Column('time_stamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['q_id'], ['questions.q_id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.quiz_id'], ),
    sa.ForeignKeyConstraint(['user_email'], ['user.user_email'], ),
    sa.PrimaryKeyConstraint('answer_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_answers')
    # ### end Alembic commands ###
